export const TRANSACTION_ACTIONS = {
  CHARGE: "CHARGE",
  REFUND: "REFUND",
  CANCEL: "CANCEL",
} as const;

export type TransactionAction = (typeof TRANSACTION_ACTIONS)[keyof typeof TRANSACTION_ACTIONS];

export const TRANSACTION_EVENT_TYPES = {
  CHARGE_SUCCESS: "CHARGE_SUCCESS",
  CHARGE_FAILURE: "CHARGE_FAILURE",
  CHARGE_REQUEST: "CHARGE_REQUEST",
  REFUND_SUCCESS: "REFUND_SUCCESS",
  REFUND_FAILURE: "REFUND_FAILURE",
  REFUND_REQUEST: "REFUND_REQUEST",
  CANCEL_SUCCESS: "CANCEL_SUCCESS",
  CANCEL_FAILURE: "CANCEL_FAILURE",
  CANCEL_REQUEST: "CANCEL_REQUEST",
} as const;

export type TransactionEventType =
  (typeof TRANSACTION_EVENT_TYPES)[keyof typeof TRANSACTION_EVENT_TYPES];
