services:
  localstack:
    image: localstack/localstack:4.5
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager,ssm,kms
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-dummy}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-dummy}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-http://host.docker.internal:4566}
      - DEBUG=${DEBUG:-0}
      - APP_CONFIG_STORE_PATH=${APP_CONFIG_STORE_PATH?:APP_CONFIG_STORE_PATH env is required}
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./tooling/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 10
